project_name: machine-agent

release:
  name_template: "v{{.Version}}"
  prerelease: auto

before:
  hooks:
    - go mod tidy

builds:
  - binary: bin/machine-agent
    main: ./cmd/machine-agent
    ldflags:
      - -s -w -X github.com/depot/machine-agent/internal/build.Version={{.Version}} -X github.com/depot/machine-agent/internal/build.Date={{time "2006-01-02"}} -X github.com/depot/machine-agent/internal/build.SentryEnvironment=release
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux]
    goarch: [amd64, arm64]

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: macOS
    format: tar.gz

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  skip: true
