name: Setup Go
description: Setup go version, cache go and goreleaser
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: "1.18"
    - uses: actions/cache@v2
      with:
        path: |
          ~/go
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go
