name: ci
on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Verify dependencies
        run: |
          go mod verify
          go mod download
      - name: Check formatting
        run: |
          STATUS=0
          assert-nothing-changed() {
            local diff
            "$@" >/dev/null || return 1
            if ! diff="$(git diff -U1 --color --exit-code)"; then
              printf '\e[31mError: running `\e[1m%s\e[22m` results in modifications that you must check into version control:\e[0m\n%s\n\n' "$*" "$diff" >&2
              git checkout -- .
              STATUS=1
            fi
          }
          assert-nothing-changed go fmt ./...
          assert-nothing-changed go mod tidy
          exit $STATUS

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          only-new-issues: false
          skip-cache: false
          skip-build-cache: true
          skip-pkg-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: 1.9.2
          args: build --rm-dist --snapshot
