name: release
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, 'dev-')
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - name: Compute tag name
        id: tag-name
        run: echo "::set-output name=tag-name::${GITHUB_REF#refs/tags/}"
      - uses: goreleaser/goreleaser-action@v3
        with:
          version: 1.7.0
          args: release --parallelism 2
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PUBLIC_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.tag-name.outputs.tag-name }}
